permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: Build Image and Push to ECR

# Only run one deployment at a time for a given branch
concurrency: ci-${{ github.ref }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    uses: tailsdotcom/actions/.github/workflows/build-container.yml@main
    with:
      aws_role: ${{ vars.AWS_ACCOUNT_NUMBER }}:role/ci-meraki-dashboard-prometheus-exporter
      image: ${{ vars.AWS_ACCOUNT_NUMBER }}.dkr.ecr.eu-west-1.amazonaws.com/infrastructure-engineering/meraki-dashboard-prometheus-exporter

  retag:
    name: Retag for prod
    if: github.ref_name == 'main'
    uses: tailsdotcom/actions/.github/workflows/retag-image.yml@main
    with:
      aws_role: ${{ vars.AWS_ACCOUNT_NUMBER }}:role/ci-meraki-dashboard-prometheus-exporter
      repository: infrastructure-engineering/meraki-dashboard-prometheus-exporter
      environment: prod
